USE Freela;
DROP TABLES IF EXISTS CONTATO, USUARIO, PUBLICACAO;
DROP DATABASE IF EXISTS Freela;

CREATE DATABASE Freela;

USE Freela;

CREATE TABLE USUARIO(
id INTEGER AUTO_INCREMENT,
cpf TEXT NOT NULL,
nome TEXT NOT NULL,
profissao TEXT NOT NULL,
imagem TEXT,
descricao TEXT,
PRIMARY KEY(id)
);

CREATE TABLE CONTATO(
id INTEGER AUTO_INCREMENT,
fonte TEXT,
link TEXT,
id_usuario INT,
PRIMARY KEY(id),
FOREIGN KEY(id_usuario) REFERENCES USUARIO(id)
);

CREATE TABLE PUBLICACAO(
id INTEGER AUTO_INCREMENT,
imagem TEXT,
descricao TEXT,
_data DATE,
horario TIME,
valor INTEGER,
requisitos TEXT,
id_usuario INTEGER,
PRIMARY KEY(id),
FOREIGN KEY(id_usuario) REFERENCES USUARIO(id)
);